school_id= 1
usernames = [
    "https://www.instagram.com/pathenryasb/",
    "https://www.instagram.com/phhspatriotsvolleyball/",
    "https://www.instagram.com/pathenry2026/",
    "https://www.instagram.com/phhsmun/",
    "https://www.instagram.com/pathenry2028/",
    "https://www.instagram.com/henrymodelun/",
    "https://www.instagram.com/patrick_henry_wrestling/",
    "https://www.instagram.com/phhs_athletics/",
    "https://www.instagram.com/phhsboyslacrosse/",
    "https://www.instagram.com/henryyearbook/",
    "https://www.instagram.com/henryfootball1/",
    "https://www.instagram.com/phhscollege25/",
    "https://www.instagram.com/phhs.youngwomeninmedicine/",
    "https://www.instagram.com/pathenrymascot/",
    "https://www.instagram.com/pathenry2025/",
    "https://www.instagram.com/phhswomensoccer/",
    "https://www.instagram.com/phhs.girlsflag/",
    "https://www.instagram.com/phhsenviro/",
    "https://www.instagram.com/henry_powderpuff/",
    "https://www.instagram.com/phhsmarchingband/",
    "https://www.instagram.com/patrickhenrywaterboys/",
    "https://www.instagram.com/phhsavid/",
    "https://www.instagram.com/phhs.blackboxtheaterco/",
    "https://www.instagram.com/phhscolorguard/",
    "https://www.instagram.com/phhscheer/",
    "https://www.instagram.com/phhs.swear/",
    "https://www.instagram.com/patrickhenrypolomamis/",
    "https://www.instagram.com/patrickhenrypolomamis/",
    "https://www.instagram.com/phhsdanceteam/",
    "https://www.instagram.com/phhs.mocktrial/",
    "https://www.instagram.com/phhsthriftstore/",
    "https://www.instagram.com/phhs.swim/",
    "https://www.instagram.com/linkcrewphhs/",
    "https://www.instagram.com/phhs_theatre/",
    "https://www.instagram.com/phhs.patsplace/"
]

# Extract usernames from URLs into a new list
instagram_usernames = [url.rstrip('/').split('/')[-1] for url in usernames]
