name: Instagram Scraper

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        
    - name: Create instagram files directory
      run: |
        mkdir -p instagram/files
        
    - name: Restore Instagram cookies from secrets
      run: |
        echo '${{ secrets.INSTAGRAM_COOKIES }}' > instagram/files/instagram_cookies.json
        
    - name: Run Instagram scraper
      env:
        SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
        SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      run: |
        python instagram_scraper.py
        
    - name: Clean up sensitive files
      if: always()
      run: |
        rm -f instagram/files/instagram_cookies.json